import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 11,
    fontFamily: "Helvetica",
    color: "#111827",
  },

  /* --- BRAND HEADER --- */
  brandBar: {
    marginBottom: 20,
  },

  brandName: {
    fontSize: 10,
    letterSpacing: 1,
    color: "#6B7280",
  },

  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 4,
    marginBottom: 12,
  },

  accentLine: {
    height: 2,
    width: 80,
    backgroundColor: "#166534",
    marginBottom: 28,
  },

  /* --- SUMMARY BLOCK --- */
  summaryBlock: {
    backgroundColor: "#F9FAFB",
    padding: 16,
    marginBottom: 28,
  },

  summaryLabel: {
    fontSize: 10,
    color: "#6B7280",
    marginBottom: 4,
  },

  summaryValue: {
    fontSize: 22,
    fontWeight: "bold",
  },

  /* --- INFO GRID --- */
  infoSection: {
    marginBottom: 24,
  },

  infoHeader: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 10,
  },

  infoRow: {
    marginBottom: 4,
  },

  divider: {
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
    marginVertical: 20,
  },

  /* --- TABLE --- */
  tableHeader: {
    flexDirection: "row",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },

  tableRow: {
    flexDirection: "row",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },

  colScope: { width: "25%" },
  colCategory: { width: "45%" },
  colValue: { width: "30%", textAlign: "right" },

  totalRow: {
    flexDirection: "row",
    paddingVertical: 10,
    marginTop: 6,
    borderTopWidth: 1.5,
    borderTopColor: "#9CA3AF",
  },

  totalText: {
    fontSize: 12,
    fontWeight: "bold",
  },

  footer: {
    position: "absolute",
    bottom: 30,
    left: 48,
    right: 48,
    fontSize: 9,
    color: "#9CA3AF",
    textAlign: "center",
  },
});

export default function ReportPDF({ report }: any) {
  if (!report || report.length === 0) {
    return (
      <Document>
        <Page size="A4" style={styles.page}>
          <Text>No report data available</Text>
        </Page>
      </Document>
    );
  }

  const first = report[0];

  const company = first?.assessments?.company_name ?? "N/A";
  const country = first?.assessments?.country ?? "—";
  const industry = first?.assessments?.industry ?? "—";

  const total = report.reduce(
    (sum: number, row: any) =>
      sum + (Number(row.value_tco2e) || 0),
    0
  );

  return (
    <Document>
      <Page size="A4" style={styles.page}>

        {/* Brand Header */}
        <View style={styles.brandBar}>
          <Text style={styles.brandName}>
            CARBONACCOUNTING PRO
          </Text>
          <Text style={styles.title}>
            Carbon Emissions Report
          </Text>
          <View style={styles.accentLine} />
        </View>

        {/* Summary Block */}
        <View style={styles.summaryBlock}>
          <Text style={styles.summaryLabel}>
            Total Emissions
          </Text>
          <Text style={styles.summaryValue}>
            {total.toFixed(2)} tCO₂e
          </Text>
        </View>

        {/* Company Info */}
        <View style={styles.infoSection}>
          <Text style={styles.infoHeader}>
            Company Information
          </Text>

          <Text style={styles.infoRow}>
            Company: {company}
          </Text>
          <Text style={styles.infoRow}>
            Country: {country}
          </Text>
          <Text style={styles.infoRow}>
            Industry: {industry}
          </Text>
          <Text style={styles.infoRow}>
            Created: {new Date().toLocaleDateString()}
          </Text>
        </View>

        <View style={styles.divider} />

        {/* Table Header */}
        <View style={styles.tableHeader}>
          <Text style={styles.colScope}>Scope</Text>
          <Text style={styles.colCategory}>Category</Text>
          <Text style={styles.colValue}>
            Emissions (tCO₂e)
          </Text>
        </View>

        {/* Table Rows */}
        {report.map((row: any, index: number) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.colScope}>
              {row.scope}
            </Text>
            <Text style={styles.colCategory}>
              {row.category}
            </Text>
            <Text style={styles.colValue}>
              {Number(row.value_tco2e || 0).toFixed(2)}
            </Text>
          </View>
        ))}

        {/* Total Row */}
        <View style={styles.totalRow}>
          <Text style={styles.colScope}></Text>
          <Text style={[styles.colCategory, styles.totalText]}>
            Total
          </Text>
          <Text style={[styles.colValue, styles.totalText]}>
            {total.toFixed(2)}
          </Text>
        </View>

        {/* Footer */}
        <Text style={styles.footer}>
          Generated by CarbonAccounting Pro • www.carbonaccountingpro.com
        </Text>

      </Page>
    </Document>
  );
}